[mainConfig]
appName = "SHC-AI"
host = "0.0.0.0"
port = 9090

[AIConfig]
apikey = "sk-ae541f0abdfc4edb878286ebc38ea629"
baseurl = "https://dashscope.aliyuncs.com/compatible-mode/v1"
modelname = "qwen-plus"


[emailConfig]
authcode = "tykakqhhimtfgfee"
email = "1215682138@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "SHCAI"
charset =  "utf8mb4"

[jwtConfig]
expire_duration= 8760
issuer= "SHC"
subject= "SHCAI"
key= "SHCAI-v1"

[rabbitmqConfig]
host= "127.0.0.1"
port= 8672
username= "root"
password= "123456"
vhost= "/"
